name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: APTs
        run: |
          sudo apt update
          sudo apt-get install g++-mingw-w64-x86-64

          git clone https://github.com/freetype/freetype
          cd ./freetype
          ./configure --host=x86_64-w64-mingw32 --disable-static
          make
          make install
