name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: APTs
        run: |
          sudo apt update
          sudo apt-get mingw-w64-x86_64-freetype
