name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: APTs
        run: |
          sudo apt update
          sudo apt-get install gcc-mingw-w64-x86-64

          git clone https://github.com/MrsRina/freetype-mingw64-w64-support
          cd ./freetype-mingw64-w64-support
          cmake -S . -B ./cmake-build -G Ninja -D CMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -D FORCE_WINDOWS=1 -D CMAKE_INSTALL_PREFIX=/usr/local/
          cmake --build ./cmake-build
          sudo cmake --install ./cmake-build
